version: "3.0"

services:
  mongo:
    image: mongo
    container_name: entrega14
    ports:
      - 27017:27017
    volumes:
      - entrega14:/data/configdb
      - entrega14:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  entrega14: {}
